version: '2'

services:
 app:
   build: .
 nginx:
   build: ./nginx
   ports:
    - 80:80
    - 445:445
   volumes:
      - ./static:/usr/src/app/static
      - /path/to/ssl.crt:/etc/ssl/ssl.crt
      - /path/to/ssl.key:/etc/ssl/ssl.key
    links:
      - app
