version: '3'

app:
  build: .
  volumes:
    - .:./usr/src/app
  ports:
    - 3000:80
  
website:
 image: php:apache
 volumes:
    - ./website:/var/www/html
 ports:
    - 3000:80
 depends_on:
   - app
