version: '2'

services:
 app:
   build: .
   ports:
    - 3000
 webpack:
    build: ./webpack
    ports:
      - "35729:35729"
    volumes:
      - .:/app
      - /app/node_modules
      - wwwroot:/wwwroot
 nginx:
   build: ./nginx
   ports:
    - 80:80
   volumes:
      - .:/usr/src/app/static
      - wwwroot:/wwwroot
volumes:
  wwwroot:
   driver: local
