version: '2'

services:
 app:
   build: .
   ports:
    - 3000
 nginx:
   build: ./nginx
   ports:
    - 80:80
   volumes:
      - .:/usr/src/app/static
      - wwwroot:/wwwroot
volumes:
  wwwroot:
   driver: local
